use-grammars = { except = [] }

# Languages servers

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[language-server.clangd]
command = "clangd"

[language-server.gleam]
command = "gleam"
args = ["lsp"]

[language-server.marksman]
command = "marksman"
args = ["server"]

[language-server.pylsp]
command = "pylsp"

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]

[language-server.vscode-css-language-server]
command = "vscode-css-language-server"
args = ["--stdio"]

[language-server.vscode-css-language-server.config]
css.validate.enable = true
provideFormatter = true

[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args = ["--stdio"]

[language-server.vscode-html-language-server.config]
provideFormatter = true

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]

[language-server.vscode-json-language-server.config]
json.validate.enable = true
provideFormatter = true

[language-server.yaml-language-server]
command = "yaml-language-server"
args = ["--stdio"]

# Languages and grammars

# - Shells

[[language]]
name = "bash"
comment-token = "#"
file-types = [
    "sh",
    "bash",
    "zshrc",
    "zshenv",
    "zlogin",
    "zlogout",
    "zprofile",
    "zsh-theme",
    "zsh",
    { glob = ".profile" },
    { glob = ".bash_login" },
    { glob = ".bash_logout" },
    { glob = ".bash_profile" },
    { glob = ".bash_history" },
    { glob = ".bash_aliases" },
    { glob = ".bashrc" },
    { glob = ".zshrc" },
    { glob = ".zshenv" },
    { glob = ".zlogin" },
    { glob = ".zlogout" },
    { glob = ".zprofile" },
    { glob = ".xprofile" },
    { glob = ".xsession" },
    { glob = ".xsessionrc" },
    { glob = "autostart" },
]
indent = { tab-width = 2, unit = "  " }
injection-regex = "(shell|bash|zsh|sh)"
language-servers = ["bash-language-server"]
scope = "source.bash"
shebangs = ["sh", "bash", "zsh"]

[[grammar]]
name = "bash"
source = { git = "https://github.com/tree-sitter/tree-sitter-bash", rev = "2fbd860f802802ca76a6661ce025b3a3bca2d3ed" }

# - Markdown

[[language]]
name = "markdown"
block-comment-tokens = { start = "<!--", end = "-->" }
file-types = [
    "md",
    "mkd",
    "mkdn",
    "mdwn",
    "mdown",
    "markdn",
    "markdown",
    "mdtext",
    "mdtxt",
    { glob = "PULLREQ_EDITMSG" },
]
indent = { tab-width = 2, unit = "  " }
injection-regex = "md|markdown"
language-servers = ["marksman"]
roots = [".marksman.toml"]
scope = "source.md"

[[grammar]]
name = "markdown"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-markdown", rev = "7fe453beacecf02c86f7736439f238f5bb8b5c9b", subpath = "tree-sitter-markdown" }

# - TOML / JSON

[[language]]
name = "toml"
comment-token = "#"
file-types = ["toml"]
indent = { tab-width = 2, unit = "  " }
injection-regex = "toml"
language-servers = ["taplo"]
scope = "source.toml"

[[grammar]]
name = "toml"
source = { git = "https://github.com/tree-sitter/tree-sitter-toml", rev = "342d9be207c2dba869b9967124c679b5e6fd0ebe" }

[[language]]
name = "json"
auto-format = true
file-types = [
    "json",
    "js.map",
    "ts.map",
    "css.map",
    { glob = ".jslintrc" },
    { glob = ".prettierrc" },
]
indent = { tab-width = 2, unit = "  " }
injection-regex = "json"
language-servers = ["vscode-json-language-server"]
scope = "source.json"

[[grammar]]
name = "json"
source = { git = "https://github.com/tree-sitter/tree-sitter-json", rev = "94f5c527b2965465956c2000ed6134dd24daf2a7" }

[[language]]
name = "jsonc"
auto-format = true
file-types = ["jsonc"]
grammar = "json"
indent = { tab-width = 2, unit = "  " }
injection-regex = "jsonc"
language-servers = ["vscode-json-language-server"]
scope = "source.json"

# - HTML / CSS / SCSS

[[language]]
name = "html"
auto-format = true
block-comment-tokens = { start = "<!--", end = "-->" }
file-types = ["html"]
indent = { tab-width = 2, unit = "  " }
injection-regex = "html"
language-servers = ["vscode-html-language-server"]
scope = "text.html.basic"

[[grammar]]
name = "html"
source = { git = "https://github.com/tree-sitter/tree-sitter-html", rev = "e4d834eb4918df01dcad5c27d1b15d56e3bd94cd" }

[[language]]
name = "css"
auto-format = true
block-comment-tokens = { start = "/*", end = "*/" }
file-types = ["css"]
indent = { tab-width = 2, unit = "  " }
injection-regex = "css"
language-servers = ["vscode-css-language-server"]
scope = "source.css"

[[grammar]]
name = "css"
source = { git = "https://github.com/tree-sitter/tree-sitter-css", rev = "f6be52c3d1cdb1c5e4dd7d8bce0a57497f55d6af" }

[[language]]
name = "scss"
auto-format = true
block-comment-tokens = { start = "/*", end = "*/" }
file-types = ["scss"]
indent = { tab-width = 2, unit = "  " }
injection-regex = "scss"
language-servers = ["vscode-css-language-server"]
scope = "source.scss"

[[grammar]]
name = "scss"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-scss", rev = "8f47fa8be72ac299cab4c6aa02668635f2dcd4be" }

# - Gleam

[[language]]
name = "gleam"
auto-format = true
comment-token = "//"
file-types = ["gleam"]
indent = { tab-width = 2, unit = "  " }
injection-regex = "gleam"
language-servers = ["gleam"]
roots = ["gleam.toml"]
scope = "source.gleam"

[[grammar]]
name = "gleam"
source = { git = "https://github.com/gleam-lang/tree-sitter-gleam", rev = "426e67087fd62be5f4533581b5916b2cf010fb5b" }

# - Python

[[language]]
name = "python"
comment-token = "#"
file-types = [
    "py",
    "pyi",
    { glob = ".pythonrc" },
    { glob = ".pythonstartup" },
    { glob = ".python_history" },
]
indent = { tab-width = 4, unit = "    " }
injection-regex = "py(thon)?"
language-servers = ["pylsp"]
roots = ["pyproject.toml", "setup.py", "poetry.lock"]
scope = "source.python"
shebangs = ["python"]

[[grammar]]
name = "python"
source = { git = "https://github.com/tree-sitter/tree-sitter-python", rev = "0dee05ef958ba2eae88d1e65f24b33cad70d4367" }

# - C/C++

[[language]]
name = "c"
block-comment-tokens = { start = "/*", end = "*/" }
comment-token = "//"
file-types = ["c"]
indent = { tab-width = 2, unit = "  " }
injection-regex = "c"
language-servers = ["clangd"]
scope = "source.c"

[[grammar]]
name = "c"
source = { git = "https://github.com/tree-sitter/tree-sitter-c", rev = "be23d2c9d8e5b550e713ef0f86126a248462ca6e" }

[[language]]
name = "cpp"
block-comment-tokens = { start = "/*", end = "*/" }
comment-token = "//"
file-types = [
    "H",
    "C",
    "h",
    "cc",
    "cu",
    "hh",
    "ii",
    "c++",
    "cpp",
    "cuh",
    "cxx",
    "h++",
    "hpp",
    "hxx",
    "inl",
    "ino",
    "ipp",
    "ixx",
    "tpp",
    "txx",
    "cppm",
    { glob = ".h.in" },
    { glob = ".hpp.in" },
]
indent = { tab-width = 2, unit = "  " }
injection-regex = "cpp"
language-servers = ["clangd"]
scope = "source.cpp"

[[grammar]]
name = "cpp"
source = { git = "https://github.com/tree-sitter/tree-sitter-cpp", rev = "0b4aa47f07d958a49260aadc87e8474b03897c23" }

# - Rust

[[language]]
name = "rust"
auto-format = true
block-comment-tokens = [
    { start = "/*", end = "*/" },
    { start = "/**", end = "*/" },
    { start = "/*!", end = "*/" },
]
comment-tokens = ["//", "///", "//!"]
file-types = ["rs"]
indent = { tab-width = 4, unit = "    " }
injection-regex = "rs|rust"
language-servers = ["rust-analyzer"]
persistent-diagnostic-sources = ["rustc", "clippy"]
roots = ["Cargo.toml", "Cargo.lock"]
scope = "source.rust"
shebangs = ["rust-script", "cargo"]

[language.auto-pairs]
'"' = '"'
'(' = ')'
'[' = ']'
'{' = '}'
'`' = '`'

[language.debugger]
name = "lldb-dap"
command = "lldb-dap"
transport = "stdio"

[[language.debugger.templates]]
name = "binary"
args = { program = "{0}" }
completion = [{ name = "binary", completion = "filename" }]
request = "launch"

[[language.debugger.templates]]
name = "binary (terminal)"
args = { program = "{0}", runInTerminal = true }
completion = [{ name = "binary", completion = "filename" }]
request = "launch"

[[language.debugger.templates]]
name = "attach"
args = { pid = "{0}" }
completion = ["pid"]
request = "attach"

[[language.debugger.templates]]
name = "gdbserver attach"
args = { attachCommands = [
    "platform select remote-gdb-server",
    "platform connect {0}",
    "file {1}",
    "attach {2}",
] }
completion = [
    { name = "lldb connect url", default = "connect://localhost:3333" },
    { name = "file", completion = "filename" },
    "pid",
]
request = "attach"

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "9c84af007b0f144954adb26b3f336495cbb320a7" }
